### ISSUE TITLE
🇰🇷 Korean Translation Tracker

### ISSUE THREAD

**Issue by yishangupenn** [perf-ai-example-org/Prompt-Engineering-Guide#292]
> **Copied from upstream:** [dair-ai/Prompt-Engineering-Guide#139](https://github.com/dair-ai/Prompt-Engineering-Guide/issues/139)
> **Original author:** @100pearlcent
> **Originally created:** 2023-04-17

---

This issue is to show the progress of the translation into Korean, originally rooted in #90.

## 📝 To-do

C L E A N

## 🙌 Done
- [x] `pages/introduction/*` by @100pearlcent & @Denny-Hwang 
- [x] `pages/techniques/*` by @Denny-Hwang 
- [x] `pages/*` by @Denny-Hwang
- [x] `pages/application/*` by @100pearlcent
- [x] `pages/models/*` by @puhuk
- [x] `pages/risks/*` by @100pearlcent
